[2024-09-15 17:19:15,876] INFO: main: WELCOME TO OUR CUSTOM LOG!!
[2024-09-16 13:25:20,584] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-16 13:25:20,595] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-16 13:25:20,597] INFO: common: created directory at: artifacts
[2024-09-16 13:25:20,600] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-16 13:25:20,601] INFO: 967806046: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-16 13:25:32,240] INFO: 967806046: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-16 14:23:53,942] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-16 14:23:53,944] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-16 14:23:53,947] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-16 14:23:53,947] INFO: common: created directory at: artifacts
[2024-09-16 14:23:53,948] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-16 14:23:53,948] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-16 14:24:09,109] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-16 14:24:09,735] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-16 14:31:33,934] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-16 14:31:33,935] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-16 14:31:33,937] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-16 14:31:33,937] INFO: common: created directory at: artifacts
[2024-09-16 14:31:33,938] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-16 14:31:33,938] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-16 14:31:45,318] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-16 14:31:45,874] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 16:10:11,574] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:10:11,617] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:10:11,627] INFO: common: created directory at: artifacts
[2024-09-17 16:10:11,631] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:10:47,264] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:10:47,275] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:10:47,277] INFO: common: created directory at: artifacts
[2024-09-17 16:10:47,279] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:11:57,484] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:11:57,487] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:11:57,490] INFO: common: created directory at: artifacts
[2024-09-17 16:11:57,491] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:12:07,920] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-09-17 16:13:38,982] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:13:38,986] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:13:38,988] INFO: common: created directory at: artifacts
[2024-09-17 16:13:38,989] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:13:40,058] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-09-17 16:33:31,159] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-17 16:33:31,161] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:33:31,164] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:33:31,164] INFO: common: created directory at: artifacts
[2024-09-17 16:33:31,165] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-17 16:33:31,165] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:33:47,654] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:33:48,333] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 16:33:48,333] INFO: main: ************************************************
[2024-09-17 16:33:48,334] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-09-17 16:33:48,334] ERROR: main: get_prepare_base_model_config() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    obj.main()
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
TypeError: get_prepare_base_model_config() missing 1 required positional argument: 'self'
[2024-09-17 16:36:53,883] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-17 16:36:53,885] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:36:53,887] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:36:53,888] INFO: common: created directory at: artifacts
[2024-09-17 16:36:53,888] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-17 16:36:53,888] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:37:05,839] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:37:06,374] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 16:37:06,375] INFO: main: ************************************************
[2024-09-17 16:37:06,375] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-09-17 16:37:06,375] ERROR: main: get_prepare_base_model_config() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    obj.main()
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
TypeError: get_prepare_base_model_config() missing 1 required positional argument: 'self'
[2024-09-17 16:43:19,448] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-17 16:43:19,450] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:43:19,451] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:43:19,452] INFO: common: created directory at: artifacts
[2024-09-17 16:43:19,452] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-17 16:43:19,452] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:43:33,793] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:43:34,366] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 16:43:34,366] INFO: main: ************************************************
[2024-09-17 16:43:34,366] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-09-17 16:43:34,368] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:43:34,370] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:43:34,370] INFO: common: created directory at: artifacts
[2024-09-17 16:43:34,370] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:43:34,372] ERROR: main: "'ConfigBox' object has no attribute 'updated_base_model_path'"
Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'updated_base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'updated_base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'updated_base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 26, in <module>
    obj.main()
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\config\configuration.py", line 38, in get_prepare_base_model_config
    updated_base_model_path=Path(config.updated_base_model_path),
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'updated_base_model_path'"
[2024-09-17 16:50:59,252] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-17 16:50:59,262] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:50:59,267] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:50:59,268] INFO: common: created directory at: artifacts
[2024-09-17 16:50:59,268] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-17 16:50:59,269] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:51:10,773] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:51:11,436] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 16:51:11,436] INFO: main: ************************************************
[2024-09-17 16:51:11,436] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-09-17 16:51:11,438] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:51:11,439] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:51:11,440] INFO: common: created directory at: artifacts
[2024-09-17 16:51:11,440] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:51:11,440] ERROR: main: __init__() got an unexpected keyword argument 'updated_base_model_path'
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    obj.main()
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\config\configuration.py", line 35, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
TypeError: __init__() got an unexpected keyword argument 'updated_base_model_path'
[2024-09-17 16:53:06,930] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:53:06,939] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:53:06,942] INFO: common: created directory at: artifacts
[2024-09-17 16:53:06,944] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:53:32,308] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:53:32,311] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:53:32,314] INFO: common: created directory at: artifacts
[2024-09-17 16:53:32,315] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:54:25,994] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:54:25,997] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:54:25,999] INFO: common: created directory at: artifacts
[2024-09-17 16:54:26,002] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:55:55,812] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:55:55,816] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:55:55,818] INFO: common: created directory at: artifacts
[2024-09-17 16:55:55,819] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:55:59,769] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:55:59,772] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:55:59,774] INFO: common: created directory at: artifacts
[2024-09-17 16:55:59,774] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:56:00,433] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:56:00,436] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:56:00,438] INFO: common: created directory at: artifacts
[2024-09-17 16:56:00,439] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:57:07,575] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:57:07,578] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:57:07,581] INFO: common: created directory at: artifacts
[2024-09-17 16:57:07,582] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:57:31,555] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:57:31,558] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:57:31,560] INFO: common: created directory at: artifacts
[2024-09-17 16:57:31,562] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:57:32,264] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-09-17 16:57:48,086] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-17 16:57:48,090] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:57:48,118] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:57:48,125] INFO: common: created directory at: artifacts
[2024-09-17 16:57:48,127] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-17 16:57:48,129] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:58:00,322] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:58:01,486] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 16:58:01,487] INFO: main: ************************************************
[2024-09-17 16:58:01,487] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-09-17 16:58:01,490] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:58:01,492] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:58:01,494] INFO: common: created directory at: artifacts
[2024-09-17 16:58:01,494] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:58:01,494] ERROR: main: __init__() got an unexpected keyword argument 'updated_base_model_path'
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    obj.main()
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\config\configuration.py", line 35, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
TypeError: __init__() got an unexpected keyword argument 'updated_base_model_path'
[2024-09-17 17:00:29,285] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-17 17:00:29,326] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 17:00:29,330] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 17:00:29,331] INFO: common: created directory at: artifacts
[2024-09-17 17:00:29,331] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-17 17:00:29,332] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 17:00:40,935] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 17:00:41,564] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 17:00:41,564] INFO: main: ************************************************
[2024-09-17 17:00:41,564] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-09-17 17:00:41,566] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 17:00:41,568] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 17:00:41,569] INFO: common: created directory at: artifacts
[2024-09-17 17:00:41,570] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 17:00:41,570] ERROR: main: __init__() got an unexpected keyword argument 'params_weights'
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    obj.main()
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\config\configuration.py", line 35, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
TypeError: __init__() got an unexpected keyword argument 'params_weights'
[2024-09-17 17:02:33,964] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-17 17:02:33,966] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 17:02:33,968] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 17:02:33,968] INFO: common: created directory at: artifacts
[2024-09-17 17:02:33,969] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-17 17:02:33,969] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 17:02:46,193] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 17:02:46,691] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 17:02:46,692] INFO: main: ************************************************
[2024-09-17 17:02:46,692] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-09-17 17:02:46,693] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 17:02:46,695] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 17:02:46,695] INFO: common: created directory at: artifacts
[2024-09-17 17:02:46,696] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 17:02:47,260] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-09-17 17:02:47,576] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 17:03:11,613] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-17 17:03:11,615] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 17:03:11,617] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 17:03:11,618] INFO: common: created directory at: artifacts
[2024-09-17 17:03:11,618] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-17 17:03:11,618] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 17:03:24,272] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 17:03:24,888] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 17:03:24,889] INFO: main: ************************************************
[2024-09-17 17:03:24,889] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-09-17 17:03:24,891] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 17:03:24,892] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 17:03:24,892] INFO: common: created directory at: artifacts
[2024-09-17 17:03:24,893] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 17:03:25,369] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-09-17 17:03:25,648] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL COMPLETED <<<<<<<<<<

x=========================x
